### ISSUE TITLE
Atom : download the latest deb instead of relying on update repositories

### ISSUE THREAD

**Issue by sporniket** [sporniket/workstation-cm#44]
Update repositories are more likely to be blocked than individual debian package from the official website. It will be easier to get and apply update.

https://atom.io/download/deb

**Comment by asaverino** [comment]
Trying this, as a student. Thanks for the advice??? lol.

**Comment by sporniket** [comment]
@asaverino to **use** the VM, study the content of `sample-seed`. You will need basic understanding of Vagrant and Virtualbox, and to install those tools if not done yet.

To **build** the VM yourself, study the other files, and you need fair understanding of Packer.

Regards.
